### ISSUE TITLE
Facebook Integration

### ISSUE THREAD

**Issue by parteek-johal** [parteek-johal/Gym-Buddy#1]
Allow the user to login and log out using their facebook account.

- [x] Splash screen with "Login Facebook" button
- [x] Clicking on button takes user to FB login
- [x] Once logged in, user taken to the Home page of the App
- [x] Retrieve basic user info like Name, Email, Profile Pic
- [x] Logout option
- [x] Once user logs out, they are taken back to Splash screen with "Login Facebook" button

**Comment by mehdiraza** [comment]
Are we open to doing this within Xcode using swift?

**Comment by mehdiraza** [comment]
Facebook integration complete. ae5cf56d434fd12f195c1899fd3ac8ba00dfe6f0
